gSoluto = float(input("Digite los gramos de soluto: "))
PM = float(input("Digite el peso molecular: "))
N = (gSoluto/PM)
print("N = gramos de soluto / peso molecular")
print("N = ",gSoluto," / ",PM)
print("N = ",N," N")
print("Los moles son ",N," N")